import os

PROJECT = 'Hongo'  
PROJECT_DIR = os.getcwd()
SRC_DIR = PROJECT_DIR + '/src'  
BUILD_DEBUG_DIR = PROJECT_DIR + '/build/debug'
BUILD_RELEASE_DIR = PROJECT_DIR + '/build/release'

common_env = Environment(CPPDEFINES={'VERSION': 1})
common_env['ENV']['LD_LIBRARY_PATH'] = os.environ['LD_LIBRARY_PATH']
common_env['ENV']['PKG_CONFIG_PATH'] = os.environ['PKG_CONFIG_PATH']
common_env.Append(CPPPATH=PROJECT_DIR)

release_env = common_env.Clone()
release_env.VariantDir(BUILD_RELEASE_DIR, SRC_DIR, duplicate=0)

debug_env = common_env.Clone()  
debug_env.Append(CPPDEFINES=['debug'])
debug_env.Append(CXXFLAGS=['-g'])
debug_env.VariantDir(BUILD_DEBUG_DIR, SRC_DIR, duplicate=0)

envs = {}
if int(ARGUMENTS.get('release', 0)):
  envs['release'] = release_env 
if int(ARGUMENTS.get('debug', 0)):
  envs['debug'] = debug_env

if envs:
  exports = ['env']
  for mode, env in envs.iteritems():  
    env.SConscript(SRC_DIR+'/SConscript', variant_dir='{}/build/{}'.format(PROJECT_DIR, mode), exports=exports)
